In [1]:
import numpy as np
import pandas as pd

La següent funció retorna el següent càlcul element a element pel vector o matriu d'entrada,

$$\begin{equation} x^2+2x+1 \end{equation}$$

In [6]:
def calcular(x):
    """
    Calcula, per cada element de `x` de forma individual, la funció
    x^2+2x+1
    
    *NO* es poden fer servir bucles ni list-comprehensions
    
    :param x: np.array amb els elemnts a calcular
    :return: np.array amb el càlcul fet
    """

    return np.array(list(map(lambda x: x**2+2*x+1,x)))

In [7]:
if __name__ == '__main__':
    print(calcular(np.random.random((2, 2))))

[[1.86514408 3.15316139]
 [3.41675434 3.44446125]]


Una altra forma de normalitzar vectors és fer que la seva mitja sigui 0 i la seva desviació estàndard sigui 1. Donat un vector $x$, el vector normalitzat $\bar{x}$ es calcula

$$\bar{x} = \frac{x - \mu_x}{\sigma_x}$$

On $\mu_x$ és la mitja i $\sigma_x$ la desviació estandard

In [33]:
def normalitzar(x):
    """
    Normalitza el vector d'entrada `x` segons la definició
    anterior.
    
    *NO* es poden fer servir bucles ni list-comprehensions
    
    :param x: np.array en forma de vector (unidimensional)
    :return: np.array en forma de vector (unidimensional)
    """
    std = np.std(x)
    mean = np.mean(x)
    return np.array(list(map(lambda x:(x-mean)/std,x)))

In [34]:
if __name__ == '__main__':
    print(normalitzar(np.random.random(5)))

[ 0.59425977 -1.37463395  0.51231612  1.2428215  -0.97476344]


In [41]:
def normalitzar_matriu_per_columnes(x):
    """
    Normalitza, segons la definició d'abans, les columnes de la
    matriu de forma independent (cada columna es normalitza per la seva
    pròpia mitja i desviació estàndard)
    
    *NO* es poden fer servir bucles ni list-comprehensions
    
    :param x: np.array en forma matricial (bidimensional)
    :return: np.array en forma matricial (bidimensional)
    """
    std_col = np.std(x, axis=0)
    mean_col = np.mean(x, axis=0)    
    return np.array(list(map(lambda x:(x-mean_col)/std_col,x)))

In [43]:
if __name__ == '__main__':
    print(normalitzar_matriu_per_columnes(np.random.random((5, 5))))

[[ 0.54824854 -0.32204822  0.64484689  0.78900436  0.42329133]
 [ 0.93730754  1.28186465  1.5574383   0.12155933 -1.21558915]
 [-1.41854885  0.82308444 -0.88133613 -1.92444367  1.23009141]
 [-0.98385942 -0.18921394 -0.15582029  0.23746297 -1.15008178]
 [ 0.91685218 -1.59368693 -1.16512878  0.77641701  0.71228819]]


In [45]:
def normalitzar_matriu_per_files(x):
    """
    Normalitza, segons la definició d'abans, les files de la
    matriu de forma independent (cada fila es normalitza per la seva
    pròpia mitja i desviació estàndard)
    
    *NO* es poden fer servir bucles ni list-comprehensions
    
    :param x: np.array en forma matricial (bidimensional)
    :return: np.array en forma matricial (bidimensional)
    """
    std_row = np.std(x, axis=1)
    mean_row = np.mean(x, axis=1)
    return np.array(list(map(lambda x:(x-mean_row)/std_row,x)))

In [46]:
if __name__ == '__main__':
    print(normalitzar_matriu_per_files(np.random.random((5, 5))))

[[ 0.5146456   1.30311992 -3.11926078 -0.39178847  0.33579768]
 [ 1.17214386 -1.34550935 -2.31420427  0.85799531  1.09265047]
 [ 0.7732748  -0.4005397   0.25775631 -0.26349139  1.05772733]
 [ 0.98588858 -0.19906636 -2.98571454 -0.91870832  0.77265479]
 [ 0.56214224  0.47950579  0.19613849 -1.83952862 -0.02049709]]


In [83]:
def calcular_mitja(x):
    """
    Calcula la mitja del vector d'entrada `x`, però qualsevol element
    NaN ha de ser tractat com si fos un 0. NO es pot modificar el
    vector original que es passa per paràmetre
    
    *NO* es poden fer servir bucles ni list-comprehensions
    
    :param x: np.array en forma vectorial (unidimensional)
    :return: float amb la mitja
    """
    print(np.isnan(x))
    print(sum(map(lambda x : if not np.isnan(x),x)))
    suma = x[0] + x[1]+ x[2] + x[3] 
    print(suma/5)
    return np.nanmean(x)

SyntaxError: invalid syntax (<ipython-input-83-355f1a8b3c76>, line 13)

In [82]:
if __name__ == '__main__':
    vec = np.random.random(5)
    vec[np.random.randint(0, 5)] = np.nan
    print(calcular_mitja(vec))

[0.6720352  0.3643687  0.8673184         nan 0.09006884]
[False False False  True False]
nan
0.4984477809449438


In [43]:
def crear_dataframe_1(usuari1, usuari2):
    """
    Donada la informació de dos usuaris, `usuari1` i `usuari2`, crea un
    pd.DataFrame que contingui cada un d'aquests usuaris com a una fila.
    La primera fila ha de tenir per índex "99" i la segona "88", de tipus STR.
    Les columnes han de tenir els següents noms:
        "Nom", "Cognom", "Data Registre", "Bitcoin"
        
    :param usuari1: Llista (nativa de python) amb les dades del primer usuari
    :param usuari2: Llista (nativa de python) amb les dades del segon usuari
    :return: DataFrame amb les dades dels usuaris
    """
    raise NotImplementedError()

In [44]:
if __name__ == '__main__':
    print(crear_dataframe_1(
        ['Mike', 'Strong', '2012-02-03', 99],
        ['Thomas', 'Weak', '2018-01-01', 0.4]
    ))

NotImplementedError: 

In [45]:
def crear_dataframe_2(x, exponent):
    """
    Donat un vector (np.arrray) i un exponent màxim, crea un 
    DataFrame de pandas on cada columna és la potència
    $x^i$ per cada $i$ entre 0 i `exponent` (incloits). Les columnes han de 
    tenir per nom "x<i>", on <i> és la potència
    
    Per exemple, donat ([1, 2, 3, 4], 2), crearà
    x0 | x1 | x2
    ------------
    1    1    1 
    1    2    4
    1    3    9
    1    4    16
    
    Els indexs de les files són 0, 1, ..., n; on n és el nombre d'elements
    a x
    
    **Pots fer servir 1 sol bucle per iterar de 0 a exponent, cap més**
    
    :param x: np.array unidimensional amb les dades per calcular potències
    :param exponent: enter >= 0, màxim exponent a fer servir
    :return: Un DataFrame de pandas, tal i com s'especifica
    """
    raise NotImplementedError()

In [46]:
if __name__ == '__main__':
    print(crear_dataframe_2(np.asarray([1, 2, 3, 4]), 5))

NotImplementedError: 

In [41]:
def consultar_basic(df):
    """
    Donat un DataFrame amb noms i notes, retorna solament
    els noms d'aquells usuaris que tinguin un 5 o més
    
    :param df: DataFrame amb dos columnes "Nom", "Nota", amb 1 o més
        files. "Nom" és una string i "Nota" un float
    :return: Un pd.Series o llista/tupla de Pandas amb els noms 
        (i solament els noms) dels alumnes amb 5 o més
    """
    raise NotImplementedError()

In [42]:
if __name__ == '__main__':
    print(consultar_basic(pd.DataFrame({
        'Nom': ['Antonio', 'Mireia'],
        'Nota': [5.1, 0.1]
    })))

NotImplementedError: 

In [63]:
def consultar_dificil(df):
    """
    De totes les files d'un DataFrame, retorna l'índex d'aquella que tingui 
    el menor nombre de NaNs
    
    *Es pot fer sense bucles, consulta la documentació de Pandas, la cheetsheet
    o stackoverflow*
    
    :param df: DataFrame sobre el que operar, les files contenen floats o NaN
    :return: L'índex (int, ja ve donat) de la fila amb menys NaNs
    """
    raise NotImplementedError()

In [64]:
if __name__ == '__main__':
    print(consultar_dificil(pd.DataFrame([
        [0, np.nan, 3.0, 2, np.nan],
        [np.nan, 1, 2, 3, 4],
        [np.nan, 0, 0, np.nan, np.nan]
    ])))

NotImplementedError: 