# Examen de Teoria (1er parcial, Gener 2019)

Totes les preguntes valen 2 punts.

**Pregunta 1**: Explica com aplicaries l'algorisme per trobar els $k$-ítems més frequents per detectar plagis en els lliuraments de treballs (em format .txt) d'un grup d'estudiants. La definició que farem servir és que **dos treballs tenen un problema de plagi si comparteixen al menys 10 frases en comú**. 

**Pregunta 2**: Un cop feta l'anàlisi per trobar els k ítems més freqüents, quin és el procés per crear un conjunt de regles? Posa algun exemple concret per il·lustrar la resposta.

**Pregunta 3**: Quina és la diferència entre un recomanador col·Laboratiu basat en ítems i un basat en usuaris? Quines avantatges/inconvenients tenen cada un d'ells? 

**Pregunta 4**: En el marc dels models probabilístics del llenguatge, podem calcular de forma exacta aquesta fòrmula? Justifa-ho.

$$
\begin{equation}
P(W_{1:n}) = P(W_n) \times P(W_{n-1} | W_{n}) \times P(W_{n-2} | W_{n-1}, W_{n}) \times \dots \times P(W_{1} | W_{2}, \dots, W_{n})
\end{equation}
$$

**Pregunta 5:** Com contaries de forma eficient el nombre d’elements diferents que surten en una seqüència molt llarga o fins i tot infinita?

<br>
<br>
<hr>
<br>
<br>

# Examen de Teoria (2on parcial, Gener 2019)

Totes les preguntes valen valen 2 punts.

**Pregunta 1**: En problemes d'exploració-explotació podem usar la funció `SoftMax` junt amb els mètodes ϵ-voraços. Quin objectiu té usar aquesta funció?

Els métodes ϵ-voraços utilitzen una petita probabilitat ϵ per explorar de forma uniformement distribuida totes les accions. D'aquesta manera quan fem moltes jugades podem asegurar que totes les accions s'han  visitat prou vegades i per tant el valor estimat s'aproxima a la realitat, no obstant té el inconvenient que totes les accions (fins hi tot les de menys valor) s'exploren per igual. Per aquest motiu la funció SoftMax permet explorar en funció dels valors estimats de les accions, de manera que esta funció distribueix en funció dels valors estimats i no de forma uniforme.

**Pregunta 2**: Com definiries una xarxa de món petit?

Una xarxa de mon petit és aquella xarxa que no te tendencia a perdre nodes (robusta en nodes). Té nodes (hub) i es caracteriza sobretot pel fet que la podem aproximar la seva funció de distribució de grau amb una funció potencial.

**Pregunta 3**: Què volem dir exactament quan diem que un algorisme potser no és sempre "just" (des d'un punt de vista ètic)? Posa algun exemple pràctic. 

Un algorisme no sempre es just quan utilitza les dades dels usuaris de manera que una gran majoria es veu recompensada pero una part d'aquesta es veu afectada negativament.
Un exemple podria ser quan es vol separar les dades dels usuaris (alguns usuaris podrien caure en una regio que no li correspon i per tant no sería just per a ells).

**Pregunta 4**: Modifica el següent programa d'optimització de manera que enlloc de treballar amb un pas fixe (``learning_rate = 0.01``) ho faci amb un pas variable i consideri a cada iteració el millor entre aquests passos: ``learning_rate = [100, 10, 1, 0.1, 0.01, 0.001, 0.0001, 0.00001]``. 

In [185]:
# NOT WORKING

In [186]:
import numpy as np
import matplotlib.pylab as plt

# generació de dades (x,y) per l'aprenentatge

def f(x): 
    return x*2

x = np.random.uniform(0,1,20)
noise_variance =0.2
noise = np.random.randn(x.shape[0])*noise_variance
y = f(x) + noise

# definició del model i de la funció de cost
def model(x, w): 
    return x * w

def cost(y, t): 
    return ((t - y)**2).sum()

#definció del gradient analític *fes la teva modificació aquí*
def gradient(w, x, y): 
    return 2 * x * (model(x, w) - y)

# definim un pas
def delta_w(w_k, x, y, learning_rate):
    return learning_rate * gradient(w_k, x, y).sum()

# valor inicial del pes
w = 0.1

# definició del pas
learning_rate = 0.01
learning_rate = [100, 10, 1, 0.1, 0.01, 0.001, 0.0001, 0.00001]

nb_of_iterations = 15  
w_cost = [(w, cost(model(x, w), y))] 
for i in range(nb_of_iterations):
    for lr in learning_rate:
        dw = delta_w(w, x, y, lr)  
        w = w - dw  
        w_cost.append((w, cost(model(x, w), y)))  

for i in range(0, len(w_cost)):
    print('w({}): {:.4f} \t cost: {:.4f}'.format(i, w_cost[i][0], w_cost[i][1]))

KeyboardInterrupt: 

**Pregunta 5**: Per què, tot i que en teoria una xarxa Multilayer Perceptron simple pot aprendre qualsevol funció (segons el *Universal Approximation Theorem*) es fan xarxes amb molts layers (*deep learning*)?

Segons allò que volguem entrenar en la nostra xarxa es requerirà més o menys layers.
Utilitzar molts layers es igual de dolent que com utilitzar pocs layers (tot depèn del problema amb què tractem).
La idea es trobar una quantitat adequada que ho faci de forma eficient i correctament.
Cada layer s'especialitza en una tasca en concret i permet que el resultat sigui més acurat per això avui dia s'utilitzen molts layers.

<br>
<br>
<hr>
<br>
<br>

# Instruccions examen pràctic

Independentment de quin examen realitzis (segon parcial o tots dos), respon l'**exercici comú**.

### Primer parcial

Si fas el primer parcial, respon l'**exercici 1**.

### Segon parcial

Pel segon parcial, respon **un dels dos exercicis**: **exercici 2A** o **exercici 2B**

In [187]:
import numpy as np
import pandas as pd

# Exercici comú

Per normalizat un vector i aconseguir que la seva mitja sigui $0$ i la seva desviació estàndard sigui $1$, s'aplica la següent equació sobre un vector $x$.

$$\bar{x} = \frac{x - \mu_x}{\sigma_x}$$

On $\mu_x$ és la mitja i $\sigma_x$ la desviació estandard.


**a) Implementa la funció *normalize_vec* amb l'exemple següent:**

[0.04396131, 0.3418877 , 0.75050176, 0.74445241, 0.46609646, 0.44790707, 0.66703217, 0.54339577]

In [188]:
def normalize_vec(x):
    """
    Normalitza el vector d'entrada `x` segons la definició
    anterior.
    
    *NO* es poden fer servir bucles ni list-comprehensions
    
    :param x: np.array en forma de vector (unidimensional)
    :return: np.array en forma de vector (unidimensional)
    """
    
    norm_vec = map(lambda y : (y-np.mean(x))/np.std(x), x)
    return(np.array(list(norm_vec)))
    

normalize_vec(np.array([0.04396131, 0.3418877 , 0.75050176, 0.74445241, 0.46609646,
       0.44790707, 0.66703217, 0.54339577]))

array([-2.07074554, -0.71988246,  1.13286261,  1.10543354, -0.15669291,
       -0.23916756,  0.75439333,  0.19379898])

**b) Implementa la funció *create_matrix* que crea matrius amb valors random.**

In [189]:
def create_matrix(shape):
    """
    Crea una matriu amb dimensió shape
    
    *NO* es poden fer servir bucles ni list-comprehensions
    
    :param shape: list o tupla amb les dimensions
    :return : np.array amb la matriu
    """
    return np.random.random(tuple(shape))

create_matrix([3,4])

array([[0.48688672, 0.63842762, 0.69501562, 0.97710569],
       [0.91290097, 0.20158977, 0.75310374, 0.16447678],
       [0.9191588 , 0.15011375, 0.77243531, 0.56667976]])

**c) Implementa la funció *normalize_matrix_by_column* utilitzant la definició anterior per a cada columna.**

In [190]:
def normalize_matrix_by_column(matrix):
    """
    Normalitza, segons la definició d'abans, les columnes de la
    matriu de forma independent (cada columna es normalitza per la seva
    pròpia mitja i desviació estàndard)
    
    *NO* es poden fer servir bucles ni list-comprehensions
    
    :param x: np.array en forma matricial (bidimensional)
    :return: np.array en forma matricial (bidimensional)
    """
    a = map(lambda x : normalize_vec(x), np.hsplit(matrix,matrix.shape[1]))
    return(np.array(list(a)))

normalize_matrix_by_column(create_matrix([3,4]))

array([[[ 0.00926875],
        [-1.22935294],
        [ 1.22008419]],

       [[ 1.34973056],
        [-0.30925544],
        [-1.04047512]],

       [[-0.91434093],
        [ 1.39150739],
        [-0.47716646]],

       [[ 0.56827942],
        [-1.40565381],
        [ 0.83737439]]])

**d) Implementa la funció *normalize_matrix_by_row* utilitzant la definició anterior per a cada fila.**

In [191]:
def normalize_matrix_by_row(matrix):
    """anterior
    Normalitza, segons la definició d'abans, les files de la
    matriu de forma independent (cada fila es normalitza per la seva
    pròpia mitja i desviació estàndard)
    
    *NO* es poden fer servir bucles ni list-comprehensions
    
    :param x: np.array en forma matricial (bidimensional)
    :return: np.array en forma matricial (bidimensional)
    """
    return normalize_matrix_by_column(matrix.T).T

normalize_matrix_by_row(create_matrix([3,4]))

array([[[-0.34394165, -1.2026137 ,  0.90852261],
        [ 1.71440588,  1.31238089, -0.94142449],
        [-0.6438164 , -0.69728233,  1.08597544],
        [-0.72664783,  0.58751514, -1.05307356]]])

<br>
<br>
<hr>
<br>
<br>

# Primer Parcial

##  Exercici 1 (Apriori):

### Els subapartat estan relacionats però són independents

Definim **suport** com al percentatge dels usuaris que tenen un producte (o combinació de productes). És a dir, **el nombre de vegades que apareix una combinació entre el número d'usuaris**

Una millor mesura que el suport és el *lift*. Donada una combinació $X$ a la que hi afegim el producte $Y$, el *lif* es defineix com a:

$$lift(X, Y) = \frac{support(X \cup Y)}{support(X) * support(Y)}$$

És a dir, el suport de la nova combinació dividit per la multiplicació del suport de la prèvia pel del nou producte.

In [ ]:
def read(x):
    df = pd.read_csv(x, index_col=0)
    df['products'] = df['products'].apply(eval)
    return df

# Conté la relació de cada usuari amb els seus producte
df = read('pp_df.csv')

# Les combinacions de N productes
df_1 = read('pp_df_1.csv')
df_2 = read('pp_df_2.csv')
df_3 = read('pp_df_3.csv')

df.head()

In [ ]:
df_2.head()

**a) Implementa *get_support* segons la definició anterior**

Recorda, nombre de vegades que apareix cada combinació dividit pel número d'usuaris

In [ ]:
def get_support(products_column):
    """
    Calcula el suport, segons la definició anterior, de cada combinació de productes
    
    **NO posis directament 5 en el denominador, calcula-ho a partir de `products_column`**
    
    :products_column: pd.Series amb el productes d'interès
    :return: pd.Series on els indexos són les combinacions i els valors el suport
    """
    raise NotImplementedError()

In [ ]:
get_support(df_1['products'])

**b) acaba d'implementar get_lift segons la definició anterior**:

Per cada combinació nova en el DataFrame *new_combinations*, calcula'n el seu *lift*. Cada fila conté:

* $X$, la combinació prèvia de tamany 2
* $XuY$, la nova combinació de tamany 3 (X amb Y afegida)

El paràmetre $Y$ de la funció és el nou producte que afegim.

**Pel suport pots fer servir la funció a continuació**

In [ ]:
import random

def get_support_2(s):
    random.seed(1)
    p = s.unique()
    return pd.Series((random.random() for _ in p), index=p)

In [ ]:
def get_lift(df, df_1, df_2, df_3, Y):
    """
    Calcula el lift dels productes a `new_combinations`
    
    :param df: Dataframe usuari -> productes
    :param df_1: Dataframe de combinacions de tamany 1
    :param df_2: Dataframe de combinacions de tamany 2
    :param df_3: Dataframe de combinacions de tamany 3
    :param Y: Nou producte que es combina amb les de tamany 2
    :return: Diccionari, pd.Series o pd.DataFrame de combinació a lift
    """
    ####################################
    # Codi ja fet, no cal modificar
    
    new_combinations = []
    
    for user, row in df_2.iterrows():
        if Y in row['products']:
            continue
            
        if Y not in df.loc[user, 'products']:
            continue
            
        new_combinations.append({
            'X': row['products'],
            'XuY': tuple(sorted(list(row['products']) + [Y]))
        })
        
    new_combinations = pd.DataFrame(new_combinations)
    
    #
    ####################################
    
    # Aplica el càlcul de lift per cada fila a *new_combinations*, pots fer servir bucles
    # Els df_x et poden servir per calcular els suports necessaris
        
    raise NotImplementedError()

In [ ]:
get_lift(df, df_1, df_2, df_3, 6)

**c) filtra les combinacions per aquelles que tinguin un lift >= 1**

No facis servir el lift de l'exercici anterior, l'apartat és independent.

In [ ]:
def filter_by_lift(df_3, lift):
    """
    Filtra per aquelles combinacions amb un lift major igual a 1
    
    :param df_3: Dataframe de combinacions de tamany 3
    :param lift: Series de combinació de producte a lift
    :return: pd:DataFrame amb les combinacions que compleixen lift >= 1
    """
    raise NotImplementedError()

In [ ]:
import random

def get_lift_2(s):
    random.seed(1)
    products = s.unique()
    return pd.Series((random.random()*2 for _ in products), index=products)

filter_by_lift(df_3, get_lift_2(df_3['products']))

<br>
<br>
<hr>
<br>
<br>

# Segon Parcial

### **INDICA QUIN EXERCICI REALITZES: < B >**
    
* Exercici 2A (Recomanador)
* Exercici 2B (Naive Bayes)

##  Exercici 2A (Recomanador)

Per fer la recomanació col·laborativa, s'utilitza una funció que ens indiqui quants cops compraria un usuari un producte donat.

Suposarem que fem servir un recomanador basat en usuaris i que la puntuació per a un usuari $u$ i ítem $j$ ve donada per la fòrmula:

$$pred(u, i) = \hat{r}_{u,i} = \frac{\sum_{p\neq u,r_{p,i}>0} sim(u, p)\cdot r_{p,i}}{\sum_{p\neq u,r_{p,i}>0} sim(u, p)}$$

On $r_{u,i}$ indica el nombre de vegades que l'usuari $u$ ha comprat l'l'ítem $i$.

Tens el codi base a continuació

**a) Implementeu una predicció escalada al domini de l'usuari.**

Els usuaris compren en diferent mesura els productes, uns més quantitat, altres menys. Fent servir la següent fórmula escalem la predicció a la mitja i desviació de l'usuari:
$$pred(u, i) = \hat{r}_{u,i} = \sigma_{r_u} \cdot \left[\mu_{r_u} + \frac{\sum_{p\neq u,r_{p,i}>0} sim(u, p)\cdot \frac{r_{p,i}-\mu_{r_p}}{\sigma_{r_p}}}{\sum_{p\neq u,r_{p,i}>0} sim(u, p)}\right]$$
on:

* $\mu_{r_u}$ és la mitjana de compres de l'usuari *u*.
* $\sigma_{r_u}$ és la desviació estàndard de l'usuari *u*.

In [ ]:
def prediction(user, item, df, similarities):
    """
    Extreu les similituds i el nombre de vegades que un usuari ha comprat un ítem
    (resp. nombre de vegades que cada usuari ha comprat l'ítem) i crida a la funció 
    anterior per calcular les prediccions.
    
    :param user: ID de l'usuari per la predicció
    :param item: ID de l'ítem per la predicció
    :param df: Dataframe que conté el nombre de vegades que un usuari 
        ha comprat en un `aisle_id`
    :param similarities: Matriu numpy de similituds
    :return : Retorna un escalar (float) amb la predicció
    
    """
    ####################################
    # Codi ja fet, no cal modificar
    
    index = df.index.get_loc(user)
    sims = similarities[index]
    counts = df.loc[:, item]
    
    #
    ####################################
    
    # Modificar o borrar per adaptar a la fórmula 
    return (sims @ counts) / np.sum(sims[counts > 0])

In [ ]:
df_counts = pd.DataFrame({
    1: [1, 2, 0, 1, 0, 0],
    2: [1, 1, 0, 0, 2, 0],
    3: [1, 2, 3, 1, 0, 1],
    4: [10, 20, 30, 10, 0, 0],
    5: [0, 0, 0, 1, 0, 0],
    6: [1, 1, 1, 1, 1, 2]
}).T

# Predicció amb similitud de Pearson, sense negatius
prediction(1, 2, df_counts, np.maximum(0, df_counts.corr().values))

## Exercici 2B (Naive Bayes)

Al lliurament de Naive Bayes vareu implementar la funció *count_words*.
Aqyesta s'encarregava de crear un diccionari on enmagatzenava el numero de cops que cada paraula apareixia en els tweets.

**a) Implementeu la funció *count_bigrams*. Aquesta funció ha de construir un diccionari que contingui tots els bigrames (seqüències de dos tokens) que es puguin trobar al text indicant el nombre d'aparicions.**

```python
{
    bigrama_1 : 88,
    bigrama_2 : 123,
    ...
}
```

In [192]:
####################################
# Codi ja fet, no cal modificar

def memo(f):
    class memodict(dict):
        def __init__(self, f):
            self.f = f
        def __call__(self, *args):
            return self[args]
        def __missing__(self, key):
            ret = self[key] = self.f(*key)
            return ret
    return memodict(f)

@memo    
def normalize(word):
    """
    Funció que donada una paraula la normalitzi
    Exemple: Taller DELS noUS USOS ---> tallers dels nous usos
    
    :param word: paraula a normalitzar
    :return : paraula normalitzada
    """
    
    # ASCII and chars/nums only
    word = ''.join(c for c in word if ord(c) < 128 and (c.isdigit() or c.isalpha()))

    # To lowercase
    word = str(word.strip().lower())
    
    return word

#
####################################

In [193]:
from collections import Counter
def count_bigrams(text):
    """
    Funció que ha de construir un diccionari que contingui tots els 
    bigrames que s'han trobat indicant el total de cops que han aparegut.
    
    Les paraules del bigrama han d'estar normalitzades amb la funció anterior
    
    :param text: Text 
    :return : Diccionari amb el format {bigram : n_repeticions, ...}
    """
    
    norm_words = []
    for w in text.split():
        norm_word = normalize(w)
        if norm_word != "":
            norm_words.append(norm_word)
    
    bigrames = []
    for i in range(len(norm_words)-1):
        bigrames.append((norm_words[i],norm_words[i+1]))
    
    count_bigrams = dict(Counter(bigrames))
    return count_bigrams

In [37]:
with open('futex.c', 'rb') as fp:
    text = fp.read().decode('utf-8')
    
bigrams = count_bigrams(text)
print(len(bigrams))

7577


**b) Calculeu la probabilitat de cada bigrama, retorna ordenat de més a menys probable**

La probabilitat es defineix com el nombre de vegadesque apareix un bigrama dividit pel total de bigrames.

Ha de retornar un diccionari de bigrama a probilitat ordenat descendentment per probabilitat

```python
{
    bigrama_1 : 0.x,
    bigrama_2 : 0.y,
    ...
}
```

In [194]:
def bigrams_probabilities(bigrams):
    # Total de bigrames que tenim
    total_bigrams = sum(bigrams.values())
    for bigram, times in bigrams.items():
        bigrams[bigram] = float(times/total_bigrams)
        
    sorted_bigrams = sorted(bigrams.items(), key=lambda x : x[1], reverse=True)
    return sorted_bigrams

bigrams_probabilities(bigrams)

[(('user', 'space'), 0.003631261863498091),
 (('of', 'the'), 0.003053561112487031),
 (('to', 'the'), 0.0029710324337711654),
 (('the', 'lock'), 0.002805975076339434),
 (('in', 'the'), 0.002723446397623568),
 (('if', 'ret'), 0.002723446397623568),
 (('the', 'futex'), 0.0025583890401918367),
 (('static', 'int'), 0.0024758603614759714),
 (('the', 'pistate'), 0.0023933316827601057),
 (('the', 'user'), 0.002228274325328374),
 (('struct', 'futexhashbucket'), 0.002228274325328374),
 (('user', 'uaddr'), 0.002228274325328374),
 (('return', 'ret'), 0.002228274325328374),
 (('if', 'the'), 0.0020632169678966427),
 (('hash', 'bucket'), 0.0018981596104649112),
 (('space', 'value'), 0.0018156309317490455),
 (('must', 'be'), 0.0018156309317490455),
 (('the', 'hash'), 0.0017331022530331797),
 (('struct', 'futexq'), 0.0017331022530331797),
 (('futexhashbucket', 'hb'), 0.0017331022530331797),
 (('struct', 'futexpistate'), 0.0016505735743173142),
 (('union', 'futexkey'), 0.0016505735743173142),
 (('return